# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0002_auto_20160804_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='browser',
            new_name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ip',
        ),
    ]
