# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0003_auto_20160808_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='feature_nbr_pixels_text',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
